user:
  name: haha
  sex: nan
spring:
  datasource:
    url: jdbc:mysql://39.106.24.103:3306/youyou_dev?useSSL=false
    username: root
    password: 1234566
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 39.106.24.103
    port: 6379
    database: 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
server:
  port: 8888
mybatis:
  mapper-locations: classpath:com.youyou.mybatis/*mapper.xml
  config-location: classpath:com.youyou.mybatis/mybatis-config.xml
shiro:
  filter-chain-definitions:
    /login: anon
#    /**: authc
shiro-redis:
  enabled: true
  redis-manager:
    host: 39.106.24.103:6379
    database: 1
logging:
  level:
    spring.repository: debug


